### ISSUE TITLE
Error in. pipeline while trying the public private load balancer template

### ISSUE THREAD

**Issue by hari-swrl** [aws-samples/aws-proton-sample-templates#36] opened 2021-06-22 15:12 UTC
Hi, I'm trying to use the public private loadbalancer template, but when tried aws cli was on 1.9.x where the aws proton is not executing , hence updated the aws cli to latest, now which is failing for this command

**aws proton --endpoint-url https://proton.$AWS_DEFAULT_REGION.amazonaws.com --region $AWS_DEFAULT_REGION update-service-instance --deployment-type CURRENT_VERSION --name $service_instance_name --service-name $service_name --spec file://./rendered_service.yaml**

Below is the log

[Container] 2021/06/22 07:57:06 Running command aws --version
981 | aws-cli/2.2.13 Python/3.8.8 Linux/4.14.225-121.362.amzn1.x86_64 exec-env/AWS_ECS_EC2 exe/x86_64.amzn.2 prompt/off
982 |  
983 | [Container] 2021/06/22 07:57:07 Running command ls
984 | aws
985 | awscliv2.zip
986 | rendered_service.yaml
987 |  
988 | [Container] 2021/06/22 07:57:07 Running command cat rendered_service.yaml
989 | instances: {}
990 |  
991 | [Container] 2021/06/22 07:57:07 Running command aws proton --endpoint-url https://proton.$AWS_DEFAULT_REGION.amazonaws.com --region $AWS_DEFAULT_REGION update-service-instance --deployment-type CURRENT_VERSION --name $service_instance_name --service-name $service_name --spec file://./rendered_service.yaml
992 |  
993 | An error occurred (ValidationException) when calling the UpdateServiceInstance operation: Spec parsing failed Cannot deserialize instance of `java.util.ArrayList<com.amazonaws.arrow.patterncommon.model.ServiceInstance>` out of START_OBJECT token
994

<br class="Apple-interchange-newline">

**Comment by hari-swrl** [comment] 2021-06-22 19:02
Hi For those, who are facing the issue, 
check your build stage, and look for AWS cli version (should be  at latest version which supports proton)
if all the commands executed properly, this fills the rendered_service.yaml
which resolves the deploy stage issue.

**Comment by rafavallina** [comment] 2021-06-22 20:17
@hari-swrl Yes! The issue is that the Proton waiters were not added to the AWS SDK, but we had them in our preview model. We are working on incorporating them to the SDK ASAP. I'll leave this open until I can confirm that they are there

**Comment by hari-swrl** [comment] 2021-06-24 09:09
@rafavallina  Thank you

**Comment by jwoehrle** [comment] 2021-06-24 14:52
Hey @rafavallina 

I've created a workaround. I'm installing aws cli v2 and then use some bash commands to check for a succeeded deployment.

Do you think this is worth a PR or do you expect the `wait` command to be available really soon?

See my changes here:
https://github.com/aws-samples/aws-proton-sample-templates/compare/main...jwoehrle:fix_api_issues?expand=1

@hari-swrl feel free to checkout my branch and try the deployment.

**Comment by rafavallina** [comment] 2021-06-24 21:18
Hey @jwoehrle. Thanks! We actually expect the waiters to be around really soon (matter of days), so I'll just hold for a week or so and we can merge this one otherwise.

**Comment by hari-swrl** [comment] 2021-06-28 18:45
hi @jwoehrle, 
this [snippet](
https://github.com/jwoehrle/aws-proton-sample-templates/blob/5544e492a7506ff664392b72e6e38959c4477c46/public-private-fargate-microservices/service/private-fargate-svc/pipeline_infrastructure/cloudformation.yaml#L127)

would work for me, thank you
 
 waiting for the waiters to come around.
 
 Also when deploying these public private  template, dns resolutions are disabled for vpc,  when tried with dig util , im unable to hit the local service endpoint. after enabling and redeploying  my service then i was able to hit the endpoint with cloud9 from within same vpc.
 
 May some configurations need to be added for the template to enable the service discovery as it's not happening with existing one.
 i'm able to communicate within same subnet, but not between public n private subnets after deploying above templates.
 @rafavallina 
 

 Thank you.

**Comment by rafavallina** [comment] 2021-06-28 23:38
@henrybravo is the author of the public-private web service template, maybe he can look at this configuration?

**Comment by rafavallina** [comment] 2021-06-30 18:51
@hari-swrl @jwoehrle The waiters are now available in the CLI v1 and v2

**Comment by hari-swrl** [comment] 2021-07-04 20:01
@rafavallina,  Thank you will start using the waiters.

**Comment by henrybravo** [comment] 2021-07-15 15:36
> @henrybravo is the author of the public-private web service template, maybe he can look at this configuration?

@rafavallina @hari-swrl [this](https://github.com/aws-samples/aws-proton-sample-templates/pull/48) pr fixes this

**Comment by JiahuiTao** [comment] 2021-07-19 19:38
pr from @henrybravo has been approved and merged.

**Closed** 2021-07-19 19:39 UTC
